netcomm: net::TcpClient Class Reference
net::TcpClient Class Reference
TCP client binding implementation.
#include <sample/net/TcpClient.hpp>
Public Member Functions
virtual void bind (const std::string &address, IBindingDelegate *delegate_)
Connects to an address specified.
virtual void bind (const std::string &address, IBindingDelegate *delegate_)
Connects to an address specified.
Private Member Functions
TcpClient ()
Must be created only by means of BindingFactory.
TcpClient ()
Must be created only by means of BindingFactory.
Friends
class BindingFactory
Detailed Description
TCP client binding implementation.
Definition at line 12 of file TcpClient.hpp.
Member Function Documentation
void net::TcpClient::bind (const std::string & address, IBindingDelegate * delegate_) virtual
Connects to an address specified.
Address string must be in the following format: IP:PORT or FQDN:PORT
Implements net::IBinding.
Definition at line 18 of file TcpClient.cpp.
References net::TcpAddress::host(), net::IBindingDelegate::onStreamCreated(), and net::TcpAddress::port().
virtual void net::TcpClient::bind (const std::string & address, IBindingDelegate * delegate_) virtual
Connects to an address specified.
Address string must be in the following format: IP:PORT or FQDN:PORT
Implements net::IBinding.
The documentation for this class was generated from the following files:
sample/net/TcpClient.hpp
net/TcpClient.cpp