netcomm: msg::Messenger Class Reference
msg::Messenger Class Reference
Messenger built on top of net library.
#include <sample/msg/Messenger.hpp>
Public Member Functions
void setMessageFactory (IMessageFactory *messageFactory)
Sets message factory which will be responsible for creating messages.
void setBindingDelegate (::msg::IBindingDelegate *bindingDelegate)
Sets new stream created event handler.
void addDelegate (::net::IStream::TId streamId, IMessengerDelegate *delegate_)
Adds delegate_ as an observer of stream's incoming data events.
void sendMessage (::net::IStream::TId streamId, TMessagePtr message)
Sends a message over the specified stream.
virtual void onStreamCreated (net::TStreamPtr stream)
virtual void onDataReceived (::net::IStream::TId streamId, const unsigned char *buf, size_t bufSize)
Is called when data are available on a stream.
virtual void onStreamDied (::net::IStream::TId streamId)
Is called when a stream has died.
void setMessageFactory (IMessageFactory *messageFactory)
Sets message factory which will be responsible for creating messages.
void setBindingDelegate (::msg::IBindingDelegate *bindingDelegate)
Sets new stream created event handler.
void addDelegate (::net::IStream::TId streamId, IMessengerDelegate *delegate_)
Adds delegate_ as an observer of stream's incoming data events.
void sendMessage (::net::IStream::TId streamId, TMessagePtr message)
Sends a message over the specified stream.
virtual void onStreamCreated (net::TStreamPtr stream)
virtual void onDataReceived (::net::IStream::TId streamId, const unsigned char *buf, size_t bufSize)
Is called when data are available on a stream.
virtual void onStreamDied (::net::IStream::TId streamId)
Is called when a stream has died.
Public Member Functions inherited from net::IBindingDelegate
virtual void onStreamCreated (::net::TStreamPtr stream)=0
Stream connection event.
virtual void onStreamCreated (::net::TStreamPtr stream)=0
Stream connection event.
Static Public Member Functions
static Messenger & instance ()
Use this method to access global singleton instance.
static Messenger & instance ()
Use this method to access global singleton instance.
Private Types
typedef std::map
< ::net::IStream::TId,
IMessengerDelegate * > TMessengerDelegates
typedef std::vector< unsigned
char > TData
typedef std::map
< ::net::IStream::TId, TData > TStreamData
typedef std::map
< ::net::IStream::TId,
IMessengerDelegate * > TMessengerDelegates
typedef std::vector< unsigned
char > TData
typedef std::map
< ::net::IStream::TId, TData > TStreamData
Private Member Functions
Messenger ()
Explicit instantiation is forbidden.
Messenger ()
Explicit instantiation is forbidden.
Private Attributes
util::ThreadMutex m_memStreamSync
Special mutex for MemoryStream access.
IMessageFactory * m_messageFactory
::msg::IBindingDelegate * m_bindingDelegate
TMessengerDelegates m_messengerDelegates
A collection of delegates for each stream.
TStreamData m_streamData
This is where data from each stream are collected until a full message is received.
Static Private Attributes
static util::ThreadMutex s_sync
static std::auto_ptr< Messenger > s_instance
Detailed Description
Messenger built on top of net library.
Allows sending/receiving messages of fixed (yet arbitrary) size.
Definition at line 42 of file Messenger.hpp.
Member Function Documentation
void msg::Messenger::onDataReceived (::net::IStream::TId streamId, const unsigned char * buf, size_t bufSize) virtual
Is called when data are available on a stream.
writeStream must be used to write().
Implements net::IStreamListenerDelegate.
Definition at line 133 of file Messenger.cpp.
References net::StreamListener::closeStream(), msg::IMessageFactory::createMessage(), net::StreamListener::instance(), m_memStreamSync, m_messengerDelegates, m_streamData, and msg::IMessengerDelegate::onMessageReceived().
virtual void msg::Messenger::onDataReceived (::net::IStream::TId streamId, const unsigned char * buf, size_t bufSize) virtual
Is called when data are available on a stream.
writeStream must be used to write().
Implements net::IStreamListenerDelegate.
Member Data Documentation
util::ThreadMutex msg::Messenger::m_memStreamSync private
Special mutex for MemoryStream access.
underlyting string_stream implementation is not thread safe even when different threads access different unrelated instances.
Definition at line 96 of file Messenger.hpp.
Referenced by onDataReceived(), and sendMessage().
The documentation for this class was generated from the following files:
sample/msg/Messenger.hpp
msg/Messenger.cpp