netcomm: net::StreamListener Class Reference
net::StreamListener Class Reference
Singleton reactor/dispatcher.
#include <sample/net/StreamListener.hpp>
Public Member Functions
void addDelegate (TStreamPtr stream, IStreamListenerDelegate *delegate_)
Adds delegate_ as an observer of stream's incoming data events.
void run ()
Runs listening loop.
void cancelRun ()
Call this method to request run() to stop listening to events.
void joinRun ()
Waits for the stop request to complete.
void writeStream (::net::IStream::TId stream, const unsigned char *buf, size_t count)
This method should be used when writing to watched stream instead of IStream::write() in order to let the StreamListener instance handle stream errors.
void closeStream (::net::IStream::TId streamId, const std::string &errorDescription)
Explicitly closes specified stream in case some higher level error occurs.
void addDelegate (TStreamPtr stream, IStreamListenerDelegate *delegate_)
Adds delegate_ as an observer of stream's incoming data events.
void run ()
Runs listening loop.
void cancelRun ()
Call this method to request run() to stop listening to events.
void joinRun ()
Waits for the stop request to complete.
void writeStream (::net::IStream::TId stream, const unsigned char *buf, size_t count)
This method should be used when writing to watched stream instead of IStream::write() in order to let the StreamListener instance handle stream errors.
void closeStream (::net::IStream::TId streamId, const std::string &errorDescription)
Explicitly closes specified stream in case some higher level error occurs.
Static Public Member Functions
static StreamListener & instance ()
Use this method to access global singleton instance.
static StreamListener & instance ()
Use this method to access global singleton instance.
Private Types
enum { LISTENER_STOPPED = 0, LISTENER_RUNNING, LISTENER_STOPPING }
StreamListener internal state.
enum { LISTENER_STOPPED = 0, LISTENER_RUNNING, LISTENER_STOPPING }
StreamListener internal state.
typedef std::map
< ::net::IStream::TId, bool > TStreamsBusy
typedef std::vector< HANDLE > THandles
typedef std::map
< ::net::IStream::TId,
TStreamPtr > TStreams
typedef std::vector
< IStreamListenerDelegate * > TDelegates
typedef std::map
< ::net::IStream::TId,
TDelegates > TStreamDelegates
typedef std::map
< ::net::IStream::TId, bool > TStreamsBusy
typedef std::vector< HANDLE > THandles
typedef std::map
< ::net::IStream::TId,
TStreamPtr > TStreams
typedef std::vector
< IStreamListenerDelegate * > TDelegates
typedef std::map
< ::net::IStream::TId,
TDelegates > TStreamDelegates
Private Member Functions
StreamListener ()
Explicit instantiation is forbidden.
void spawnWorkerThread ()
Creates a worker thread. Must be executed under a sync.
void listenStreams ()
Worker routine, runs on multiple threads.
void streamDied (::net::IStream::TId, const std::string &errorDescription)
Must NOT be executed under a lock.
TStreamPtr getNextStream (TDelegates &delegates, bool &indexReset)
Must be executed under a lock.
TStreamPtr getStreamById (::net::IStream::TId streamId) const
Must be executed under a lock.
StreamListener ()
Explicit instantiation is forbidden.
void spawnWorkerThread ()
Creates a worker thread. Must be executed under a sync.
void listenStreams ()
Worker routine, runs on multiple threads.
void streamDied (::net::IStream::TId, const std::string &errorDescription)
Must NOT be executed under a lock.
TStreamPtr getNextStream (TDelegates &delegates, bool &indexReset)
Must be executed under a lock.
TStreamPtr getStreamById (::net::IStream::TId streamId) const
Must be executed under a lock.
Static Private Member Functions
static DWORD WINAPI workerThreadFunc (LPVOID param)
Worker thread start routine.
static DWORD WINAPI workerThreadFunc (LPVOID param)
Worker thread start routine.
Private Attributes
enum net::StreamListener:: { ... } m_state
StreamListener internal state.
bool m_stopped
HANDLE m_hEventStopping
HANDLE m_hEventStopped
size_t m_maxWorkerThreadCount
Maximum allowed number of threads.
size_t m_streamIndex
Index of a next to check stream.
TStreamsBusy m_streamsBusy
Busy flags for each stream, true indicates that this stream is being read, thus cannot be read by another worker thread.
THandles m_workerThreads
TStreams m_streams
TStreamDelegates m_streamDelegates
enum net::StreamListener:: { ... } m_state
StreamListener internal state.
Static Private Attributes
static util::ThreadMutex s_sync
static std::auto_ptr
< StreamListener > s_instance
Detailed Description
Singleton reactor/dispatcher.
Global listener of stream incoming data.
Definition at line 34 of file StreamListener.hpp.
Member Function Documentation
void net::StreamListener::cancelRun ()
Call this method to request run() to stop listening to events.
This method is non-blocking and can be used from within the IStreamListenerDelegate's methods. Call joinRun() to wait for run() to complete (but not from IStreamListenerDelegate's methods).
Definition at line 145 of file StreamListener.cpp.
References m_state.
void net::StreamListener::cancelRun ()
Call this method to request run() to stop listening to events.
This method is non-blocking and can be used from within the IStreamListenerDelegate's methods. Call joinRun() to wait for run() to complete (but not from IStreamListenerDelegate's methods).
TStreamPtr net::StreamListener::getNextStream (TDelegates & delegates, bool & indexReset) private
Must be executed under a lock.
Gets next stream (as identified by m_strewamIndex) in a round-robin fashion. Returns NULL pointer if no streams available.
Definition at line 252 of file StreamListener.cpp.
References getStreamById(), m_streamIndex, and m_streamsBusy.
Referenced by listenStreams().
TStreamPtr net::StreamListener::getNextStream (TDelegates & delegates, bool & indexReset) private
Must be executed under a lock.
Gets next stream (as identified by m_strewamIndex) in a round-robin fashion. Returns NULL pointer if no streams available.
TStreamPtr net::StreamListener::getStreamById (::net::IStream::TId streamId) const private
Must be executed under a lock.
Looks up a stream by its ID.
Definition at line 327 of file StreamListener.cpp.
Referenced by getNextStream(), and writeStream().
TStreamPtr net::StreamListener::getStreamById (::net::IStream::TId streamId) const private
Must be executed under a lock.
Looks up a stream by its ID.
void net::StreamListener::joinRun ()
Waits for the stop request to complete.
Do not call this method from within of any IStreamListenerDelegate's methods, it will cause a deadlock.
void net::StreamListener::joinRun ()
Waits for the stop request to complete.
Do not call this method from within of any IStreamListenerDelegate's methods, it will cause a deadlock.
Definition at line 158 of file StreamListener.cpp.
References m_state.
void net::StreamListener::run ()
Runs listening loop.
Call to this function blocks until stop (from some other thread or from within a delegate) is called.
void net::StreamListener::run ()
Runs listening loop.
Call to this function blocks until stop (from some other thread or from within a delegate) is called.
Definition at line 185 of file StreamListener.cpp.
References m_state, m_streamIndex, m_streamsBusy, and net::IStreamListenerDelegate::onStreamDied().
void net::StreamListener::streamDied (::net::IStream::TId streamId, const std::string & errorDescription) private
Must NOT be executed under a lock.
Acquires a lock itself. Notifies all delegates of a stream error and removes the stream from a list of listened streams.
Definition at line 448 of file StreamListener.cpp.
References net::IStreamListenerDelegate::onStreamDied().
Referenced by closeStream(), listenStreams(), and writeStream().
void net::StreamListener::streamDied (::net::IStream::TId , const std::string & errorDescription) private
Must NOT be executed under a lock.
Acquires a lock itself. Notifies all delegates of a stream error and removes the stream from a list of listened streams.
void net::StreamListener::writeStream (::net::IStream::TId stream, const unsigned char * buf, size_t count)
This method should be used when writing to watched stream instead of IStream::write() in order to let the StreamListener instance handle stream errors.
This call is blocking.
void net::StreamListener::writeStream (::net::IStream::TId stream, const unsigned char * buf, size_t count)
This method should be used when writing to watched stream instead of IStream::write() in order to let the StreamListener instance handle stream errors.
This call is blocking.
Definition at line 419 of file StreamListener.cpp.
References getStreamById(), and streamDied().
Referenced by msg::Messenger::sendMessage().
The documentation for this class was generated from the following files:
sample/net/StreamListener.hpp
net/StreamListener.cpp